### ISSUE TITLE
Copy for OSCAL 2019 poster

### ISSUE THREAD

**Issue by rskikuli** [OpenLabsHackerspace/OSCAL-branding#1]
Kjo eshte repo e sakte per te publikaur kete @silvaarapi ? Gjithsesi ky eshte propozimi per tekstin kryesor ne posterin e OSCAL 2019:

> 
> Open Source Conference Albania 
> Edition VI of the international annual conference in Albania organized by Open Labs to promote software & hardware freedom, online privacy, open data and technologies that empower the commons. 

Elemente te tjera qe kemi pasur vitin e kaluar qe propozoj mos i ndryshojme jane si me poshte:

- 18 & 19 May 2019
- Website & info: oscal.openlabs.cc
- Venue: Ofiçina, Tirana
- #OSCAL2019 #EthicalTech
- organized by Open Labs

Si mendon @silvaarapi ?

**Comment by silvaarapi** [comment]
Lets proceed with this proposal @rskikuli @kleidieski, we discussed it with the team as well and we all agreed to this.
