### ISSUE TITLE
OSCAL 2019: list of deliverables

### ISSUE THREAD

**Issue by rskikuli** [OpenLabsHackerspace/OSCAL-branding#2]
Hey @silvaarapi I opened this issue for:

- list of deliverables
- deliverable update

**Comment by silvaarapi** [comment]
Lista me deliverables si me poshte: 

- [ ] OSCAL new logo (for social networks). 
- [ ] Facebook cover (generic)
- [ ] Facebook event image
- [ ] Gif banners
- [ ] Twitter Cover
- [ ] Poster Ethical Tech (with sponsors)
- [ ] Poster Ethical Tech (without sponsors)
- [ ] Promo image: agenda
- [ ] Promo image (s): countdown
- [ ] Promo image: sponsors & partners
- [ ] Promo image: speakers
- [ ] Promo image: instagram promo
- [ ] Canta
- [ ] T-shirts (Volunteer + Organizer)

**Comment by sidorelauku** [comment]
@kleidieski can we use web proposals already, which are here:
https://github.com/OpenLabsHackerspace/OSCAL-branding/tree/master/2019_Web%20and%20Social

Or are you still working on these?

**Comment by kleidieski** [comment]
@sidorelauku Sure!

**Comment by rskikuli** [comment]
Updated the list of materials with the comments from the meeting today. Thanks @kleidieski .

**Comment by kleidieski** [comment]
Updated the list of materials removing Kids: perparese

**Comment by kleidieski** [comment]
Updated the list of materials adding:
- Promo image: venue
- Promo image: registration

**Comment by sidorelauku** [comment]
This is finished. I'm closing.
