### ISSUE TITLE
OSCAL 2019: Roll Up Version

### ISSUE THREAD

**Issue by kleidieski** [OpenLabsHackerspace/OSCAL-branding#4]
Please choose :)

https://github.com/OpenLabsHackerspace/OSCAL-branding/tree/master/2019_Roll%20Up/Roll%20Up_Proposals

**Comment by AnXh3L0** [comment]
I vote for version 1

**Comment by sidorelauku** [comment]
I vote for version 1 also.

**Comment by silvaarapi** [comment]
I also vote for 1.

**Comment by rskikuli** [comment]
Let's proceed with version nr.1 @kleidieski . Many thanks.
