### ISSUE TITLE
OSCAL 2019: removing 'draft' folders

### ISSUE THREAD

**Issue by rskikuli** [OpenLabsHackerspace/OSCAL-branding#5]
I would propose to remove the 'draft' materials when possible @kleidieski in order to avoid confusion.

**Comment by kleidieski** [comment]
I need tech help with deleting. 
Can someone with the skills feel free to delete them? Thanks!
I'll avoid uploading draft materials altogether.

**Comment by rskikuli** [comment]
Can you help @anxhelo?

**Comment by rskikuli** [comment]
Thanks Anxhelo. You are awesome. Closing this.
